# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Smartshirt Companion App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'DropDown'

  # Pods for Smartshirt Companion App

  target 'Smartshirt Companion AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Smartshirt Companion AppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
